server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviehub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: h2
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtpdm.aliyun.com
    username: noreply@moviehub.astralbridge.space
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.auth: true

mybatis-plus:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: space.astralbridge.spring.moviehub.entity

jwt:
  # noinspection SpellCheckingInspection
  secret_key: VeRbcqTLxzA2Bb3qV6qGAYg+ulP1gt+Q+W9WmnraZfs=
  expiration: 86400000 # 24小时(毫秒)

file:
  upload-dir: runtime/upload

logging:
  level:
    org.springframework.security: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

alipay:
  app_id: 2021000148638438
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrKGGILxM5fRm64bOm7wxUBhTHny9xCxTALslBMApUwNVmeubYnttpzrxOPWNXmcMuGoeB5IVFS/nfnNMFaYwRJo5GMJV58PkvqrqDmK8WiFNfTHGpvRUBjO+B7e0/7LUVwjt5jzQvR3S+Z2sTDboFhxpfXozfl5/9wDMvZTnAnFauhwZ4UHWkKf/+oHmcRDDeKBNyCwcGSyQewKfwnpnQB9lIYX+lnGGuwQaDP3nvqU61eOSzUTwhvfTBHU1/hmKX7+HQytX3eDHAjdsedix9Q4iWOh+rB+SCU7if+elHRUZjZCDkvpm2zG3a33pKGJ0uBRsG0qF2CF9LMfTd+XV9AgMBAAECggEBAJdh7unRoTJOuKw3Jnu2oPPMMSLiY8abI25bszuJ7wlJSTYL7BOaZbxu0tRsrWn0oNItOr8jTNCew1IJVgdKdE1TCbGBFSQ2g1+qpK7yI6JNT1hRt5KGn4awjcIgm5/Xj86/7XS1uVU74UDrHaRLlsV+2k+RxA2bATIhheQcpvj4l/9Ca91SshPQRqgrrnAjN1YfqfyGXz8bvXRLGk4ADMagDlHL5lFLJRaI5fXtBQTnjKoL/KbMbmeMU0lGJ2cgvBifm47AGxSUcLpLhhUmUxrIjntXtaZziTPu2FPvmsleZH8gNC1mlk2qf+KnC6GKc00fOE4Y5zRqiM5QbPm1tOECgYEA8bX2ax//j6yqh6uExexaJXlcRuDvnFagUzFY65qjnSIwEybakoKrSOXgXk8cR72deqBuy/xMHDSjBEOifrJuLJMphUWydcbdu82tyCTFz1U5qbeACP2zk5Kp44fTepxS0+6Oe8Ys98VWWgdA5hSzG4gHC8mq8M8njpFWWAfHLgUCgYEAtUasKRnmcBSXjQbrG/3QMWDRHbNj9mYTa/92LwbCxnx0UMgq+sTtNWngDL/g9DBSPxF49JSVo6AEY8QSCH8br47ZD1r2M7IHoBm/crU7ZbTIo2lk3l71X2cFu7tJGku9nRTtldTVLeCoUQ9mo4o5GqQNIYoO0vUfDjVL/hhoyxkCgYBYAb7lJlNwxpeYqlS/k90Gw/dbP08/BzN81vzfXACyl94VOxJeQgGHm1tkOz26yUlrerqcvxIfOvMX/GBP7Tu8MyDtC4F87JmTZcIem3UClq9WIiAWJfmag84jsDLJ890cmUF7w55f4JQeV4HDxEmqfo7CNf1tjJ+Eg1qC1uIo2QKBgAcz46tOaCWT6+GioLzf/OG5YxW3BwXHUIY+BEgiEKMqVsTO70Y/hN1Wc5yOEzYgpWP0IcY2ESwLM6FzLPRBeKwlFOLTTm0Had4mp8C7Cr0jzcUQbv2W8FD2Gvg2nNT6pXIUXsxRRJcqEgYGgqGE4Hf6hLsMbUJckvtRis9x0NghAoGAOposfZZLL6x07qj5s0Mng190//t+QlmIZK/wMOyRz82DPb3gPaACJ8kJPdomfLFfE5EEF2dL8QgWWJn+MuAL20Q50IyV5Cib8LbzMEaqnDEy2tJ/j6MguzaTdjBQtHyEg9oxUaHJeyoxQnCdPtdEN6m6uU50h9mvZV/nPK0WevU=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj9RV5nHgMwVlOtuwMQ8s0mzHI9iTsyxdDdGhS5RXwDJLxtVNHxmUnurJ0pFuo9tP30J6xIyG2ifMKNEyLjlKIvVebw+palrR43egPJXraN5pRV1Gj+PSENqzsLdXEVqC9BWyUKRfXY0ejqyTOURAfCTtbpd+dgQ3ncBLirO5obrq5umdSed8rdNWlYl6Ng3DlfP874JMkPWSHEo1KLd5Bbk31osIrJSM3X6loN5ha3ygBncmXvPNpN+qUdQ2xWu18tE9/xwTnfuUH4XwZ00b336ZJSTFNOZy2fkoRvq8kQ3AfXPtlYhVBX8hTb9fVqeYQrrKcX0TXcdrygUScTq8VwIDAQAB
  gateway_url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  return_url: http://localhost:8080/api/payment/return
  sign_type: RSA2
  vip_prices:
    monthly: 30.00
    yearly: 298.00
